//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavlenkoFrolovaTestIconomika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PavlenkoFrolovaTestIconomikaEntities : DbContext
    {
        public PavlenkoFrolovaTestIconomikaEntities()
            : base("name=PavlenkoFrolovaTestIconomikaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Group> Group { get; set; }
        public DbSet<Journal> Journal { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<Test> Test { get; set; }
    }
}
